print("Give me a word!")
word = input()
print("Give me a second word!")
word = input()
print("Great, now your favorite number?")
word = input()
print("And your second-favorite number...")
word = input()
print("Whew!  Wasn't that fun?")
