print("Please enter the following information so I can sell it for a profit!")
first_name = input("First name: ")
last_name = input("Last name: ")
grade = input("Grade (9-12): ")
id = input("Student ID: ")
login = input("Login: ")
average = input("Average: ")

print("Your information: ")
print(f"Login:     {login}")
print(f"ID:        {id}")
print(f"Name:      {first_name}, {last_name}")
print(f"Average:   {average}% ")
print(f"Grade:     {grade}")
